[install]
is_configured = 0

[ui]
is_visible = 1
label = AWS DFD Visualizer

[launcher]
author = Security Architect
description = Interactive AWS Data Flow Diagrams (DFD) for Splunk. Visualizes AWS Config topologies, nested VPCs/Subnets, and Zero-Trust compliance highlights.
version = 2.8.0

[id]
name = AWS-DFD-Visualizer
version = 2.8.0

[package]
id = AWS-DFD-Visualizer
check_for_updates = 1
