/**
 * src/components/AwsDfdVisualizer/stencils/aliases.js
 * 
 * Hand-curated shorthand alias maps for cloud provider stencils.
 * Maps commonly used user abbreviations or short keys directly to canonical
 * catalog tokens (e.g. S3 -> SIMPLESTORAGESERVICE, ALB -> ELASTICLOADBALANCING).
 * 
 * NOTE: Values here must always be uppercase catalog tokens, NOT filenames or paths.
 */

export const AWS_ALIASES = {
    'S3': 'SIMPLESTORAGESERVICE',
    'BUCKET': 'SIMPLESTORAGESERVICE',
    'ALB': 'ELASTICLOADBALANCING',
    'ELB': 'ELASTICLOADBALANCING',
    'LOADBALANCER': 'ELASTICLOADBALANCING',
    'ELASTICLOADBALANCINGV2': 'ELASTICLOADBALANCING',
    'ASG': 'EC2AUTOSCALING',
    'AUTOSCALINGGROUP': 'EC2AUTOSCALING',
    'IAM': 'IDENTITYANDACCESSMANAGEMENT',
    'ISSO': 'IDENTITYANDACCESSMANAGEMENT',
    'WAFV2': 'WAF',
    'WEBACL': 'WAF',
    'FIREHOSE': 'DATAFIREHOSE',
    'DELIVERYSTREAM': 'DATAFIREHOSE',
    'PDP': 'VERIFIEDPERMISSIONS',
    'POLICYENGINE': 'VERIFIEDPERMISSIONS',
    'LAMBDA': 'LAMBDA',
    'TRAIL': 'CLOUDTRAIL',
    'ALARM': 'CLOUDWATCH',
    'DBINSTANCE': 'RDS',
    'DBCLUSTER': 'AURORA',
    'DISTRIBUTION': 'CLOUDFRONT',
    'DIRECTORYSERVICE': 'DIRECTORYSERVICE',
    'DIRECTORY': 'DIRECTORYSERVICE',
    'SHIELD': 'SHIELD'
};

export const AZURE_ALIASES = {
    'VM': 'VIRTUALMACHINE',
    'VMS': 'VIRTUALMACHINES',
    'VIRTUAL_MACHINE': 'VIRTUALMACHINE',
    'VIRTUAL_MACHINES': 'VIRTUALMACHINES',
    'BLOB_STORAGE': 'STORAGEACCOUNTS',
    'BLOB': 'STORAGEACCOUNTS',
    'STORAGE_ACCOUNT': 'STORAGEACCOUNTS',
    'STORAGE_ACCOUNTS': 'STORAGEACCOUNTS',
    'SQL_DATABASE': 'SQLDATABASE',
    'SQL_DATABASES': 'SQLDATABASES',
    'APP_SERVICE': 'APPSERVICE',
    'APP_SERVICES': 'APPSERVICES',
    'FUNCTION_APP': 'FUNCTIONAPP',
    'FUNCTION_APPS': 'FUNCTIONAPPS',
    'ACTIVE_DIRECTORY': 'ENTRADOMAINSERVICES',
    'ENTRA': 'MANAGEDIDENTITIES',
    'ENTRA_ID': 'MANAGEDIDENTITIES',
    'MANAGED_IDENTITY': 'MANAGEDIDENTITY',
    'MANAGED_IDENTITIES': 'MANAGEDIDENTITIES',
    'ROUTE_TABLE': 'ROUTETABLE',
    'ROUTE_TABLES': 'ROUTETABLES',
    'APP_GATEWAY': 'APPLICATIONGATEWAY',
    'APPLICATION_GATEWAY': 'APPLICATIONGATEWAY',
    'APPLICATION_GATEWAYS': 'APPLICATIONGATEWAYS',
    'FRONT_DOOR': 'FRONTDOORANDCDNPROFILE',
    'FRONTDOOR': 'FRONTDOORANDCDNPROFILE',
    'KEY_VAULT': 'KEYVAULT',
    'KEY_VAULTS': 'KEYVAULTS',
    'VNET': 'VIRTUALNETWORK',
    'VNETS': 'VIRTUALNETWORKS',
    'VIRTUAL_NETWORK': 'VIRTUALNETWORK',
    'VIRTUAL_NETWORKS': 'VIRTUALNETWORKS',
    'NSG': 'NETWORKSECURITYGROUP',
    'NETWORK_SECURITY_GROUP': 'NETWORKSECURITYGROUP',
    'AKS': 'KUBERNETESSERVICES',
    'KUBERNETES': 'KUBERNETESSERVICES'
};

export const GCP_ALIASES = {
    'COMPUTE': 'COMPUTEENGINE',
    'COMPUTE_ENGINE': 'COMPUTEENGINE',
    'INSTANCE': 'COMPUTEENGINE',
    'VM': 'COMPUTEENGINE',
    'GCE': 'COMPUTEENGINE',
    'CLOUD_STORAGE': 'CLOUDSTORAGE',
    'CLOUD_SQL': 'CLOUDSQL',
    'APP_ENGINE': 'APPENGINE',
    'SERVICE_ACCOUNT': 'SERVICEACCOUNT',
    'VPC_NETWORK': 'VPCNETWORK',
    'LOAD_BALANCER': 'LOADBALANCER'
};

export const ALIAS_REGISTRY = {
    aws: AWS_ALIASES,
    azure: AZURE_ALIASES,
    gcp: GCP_ALIASES
};
