// Auto-generated by scripts/generate-stencil-catalog.js. Do not edit directly.
export const GCP_CATALOG = [
    {
        "path": "gcp/compute/app-engine.svg",
        "tokens": [
            "APPENGINE",
            "COMPUTE"
        ],
        "category": "COMPUTE"
    },
    {
        "path": "gcp/compute/compute-engine.svg",
        "tokens": [
            "COMPUTEENGINE",
            "COMPUTE"
        ],
        "category": "COMPUTE"
    },
    {
        "path": "gcp/database/cloud-sql.svg",
        "tokens": [
            "CLOUDSQL",
            "DATABASE"
        ],
        "category": "DATABASE"
    },
    {
        "path": "gcp/identity/iam.svg",
        "tokens": [
            "IAM",
            "IDENTITY"
        ],
        "category": "IDENTITY"
    },
    {
        "path": "gcp/identity/service-account.svg",
        "tokens": [
            "SERVICEACCOUNT",
            "IDENTITY"
        ],
        "category": "IDENTITY"
    },
    {
        "path": "gcp/networking/cdn.svg",
        "tokens": [
            "CDN",
            "NETWORKING"
        ],
        "category": "NETWORKING"
    },
    {
        "path": "gcp/networking/load-balancer.svg",
        "tokens": [
            "LOADBALANCER",
            "NETWORKING"
        ],
        "category": "NETWORKING"
    },
    {
        "path": "gcp/networking/route.svg",
        "tokens": [
            "ROUTE",
            "NETWORKING"
        ],
        "category": "NETWORKING"
    },
    {
        "path": "gcp/networking/subnet.svg",
        "tokens": [
            "SUBNET",
            "NETWORKING"
        ],
        "category": "NETWORKING"
    },
    {
        "path": "gcp/networking/vpc-network.svg",
        "tokens": [
            "VPCNETWORK",
            "NETWORKING"
        ],
        "category": "NETWORKING"
    },
    {
        "path": "gcp/security/armor.svg",
        "tokens": [
            "ARMOR",
            "SECURITY"
        ],
        "category": "SECURITY"
    },
    {
        "path": "gcp/security/firewall.svg",
        "tokens": [
            "FIREWALL",
            "SECURITY"
        ],
        "category": "SECURITY"
    },
    {
        "path": "gcp/storage/cloud-storage.svg",
        "tokens": [
            "CLOUDSTORAGE",
            "STORAGE"
        ],
        "category": "STORAGE"
    }
];

export const GCP_TOKEN_MAP = {
    "APPENGINE": "gcp/compute/app-engine.svg",
    "COMPUTE": "gcp/compute/compute-engine.svg",
    "COMPUTEENGINE": "gcp/compute/compute-engine.svg",
    "CLOUDSQL": "gcp/database/cloud-sql.svg",
    "DATABASE": "gcp/database/cloud-sql.svg",
    "IAM": "gcp/identity/iam.svg",
    "IDENTITY": "gcp/identity/iam.svg",
    "SERVICEACCOUNT": "gcp/identity/service-account.svg",
    "CDN": "gcp/networking/cdn.svg",
    "NETWORKING": "gcp/networking/cdn.svg",
    "LOADBALANCER": "gcp/networking/load-balancer.svg",
    "ROUTE": "gcp/networking/route.svg",
    "SUBNET": "gcp/networking/subnet.svg",
    "VPCNETWORK": "gcp/networking/vpc-network.svg",
    "ARMOR": "gcp/security/armor.svg",
    "SECURITY": "gcp/security/armor.svg",
    "FIREWALL": "gcp/security/firewall.svg",
    "CLOUDSTORAGE": "gcp/storage/cloud-storage.svg",
    "STORAGE": "gcp/storage/cloud-storage.svg"
};

export const GCP_CATEGORY_DEFAULT_MAP = {
    "COMPUTE": "gcp/compute/compute-engine.svg",
    "DATABASE": "gcp/database/cloud-sql.svg",
    "IDENTITY": "gcp/identity/iam.svg",
    "NETWORKING": "gcp/networking/cdn.svg",
    "SECURITY": "gcp/security/armor.svg",
    "STORAGE": "gcp/storage/cloud-storage.svg"
};
